In [3]:
import numpy as np
#HOW TO CREATE NUMPY ARRAYS

In [7]:
#1) convert python list into numpy array
mylist = [1,2,3]

In [11]:
mylist

[1, 2, 3]

In [13]:
myarr = np.array(mylist)

In [15]:
myarr

array([1, 2, 3])

In [17]:
type(myarr)

numpy.ndarray

In [19]:
my_matrix = [[1,2,3],[4,5,6]]


In [21]:
my_matrix


[[1, 2, 3], [4, 5, 6]]

In [23]:
np.array(my_matrix)
#converts it into a 2D

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#2) Using built in functions

In [29]:
np.arange(0,10,2)
#w one 'r'!
#equivalent to 'range' function in python
#w shift+tab i can see info about the function --> arange([start,] stop[, step,], dtype=None, *, like=None)
#w the (0,10) will go all the way from 0 to 10 without including the 10 --> UP TO BUT NOT INCLUDING
#3 w the (0,10,2) will go fron 0 to 10 without includiong 10 but w a stepsize of 2 (de dos en dos)

array([0, 2, 4, 6, 8])

In [31]:
np.arange(0,100,20)
#wont include 100! careful --> id have to put 202 if i want the 100 included

array([ 0, 20, 40, 60, 80])

In [37]:
np.zeros((5,2))
#will return zeros as FLOATING POINT NUMBERS
#gotta put 4 parenthesis if i want 2D
#1º rowa; 2º columns!!!

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.linspace(0,10,3)
#will take a start, a stop and a 'num' (how many numbers i want btw start and stop 
# --> linearly/evenly spaced over that interval)

array([ 0.,  5., 10.])

In [51]:
np.linspace(0,10,11)
#cos it INCLUDES THE STOPPING POINT --> from 0 to 10 are 11 numbers --> you always have to add one more
#all floats for precission

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [57]:
#if i checke the len of that result, should be the same as the 'num' entered
len(np.linspace(0,10,11))

11

In [63]:
np.eye(5)
#will create an identity matrix == ssquare matrix = same n of columns and row and ones in the diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
#TO CREATE RANDOM DISTRIBUTIONS OF DATA:
np.random.rand(5,2)
#Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``. - where 0 inclusive and 1 exclusive -- can return 0 but not 1
#uniform distribution --> all the numbers in btw 0 and 1 have the same likelihood of being picked
#WILL PICK ME A RANDOM NUMBER BTW 0 AND 1 (NEVER 1), AND ALL OF THEM HAVE THE SAME LIKELIHOOD OF BEING RETURNED
#AND AGAIN I CAN MAKE IT 2D (1º ROWS; 2º COLUMNS)
#tab allow me to see all possible functions with that beginning

array([[0.70518023, 0.38645839],
       [0.31011011, 0.8541646 ],
       [0.37650104, 0.29520378],
       [0.14617493, 0.12781209],
       [0.76371131, 0.84367676]])

In [75]:
#for a standard normal distribution
np.random.randn(10)
#Return a sample (or samples) from the "standard normal" distribution
#mean 0 and variance 1
# --> i can get negative numbers, however the numbers that are closest to 0 have a higher likelihood of being selected (bc of the 'standard normald'

array([-1.0254556 ,  0.48550392,  1.27381796, -0.17877077, -0.6086514 ,
       -0.68964659,  1.124312  , -1.25963518,  1.0280196 ,  0.34857438])

In [77]:
np.random.randn(2,3)

array([[-0.15215619,  0.44791207, -0.17942882],
       [-0.62756796, -0.75889004,  0.03301836]])

In [81]:
np.random.randint(9,10,5)
#Return random integers from the "discrete uniform" distribution of the 
    #specified dtype in the "half-open" interval [`low`, `high`). If `high` is None (the default), 
    #then results are from [0, `low`).

array([9, 9, 9, 9, 9])

In [87]:
#this happens bc 10 is not included and intergers are not decimals (only whole numbers)!!! --> the only possibility is all nines

In [91]:
np.random.randint(0,101,(4,5))
<3can also pass it for 2D

array([[35, 12,  1, 76, 12],
       [49, 76, 48, 59, 71],
       [54, 44, 39, 53, 50],
       [70, 83,  4, 52,  0]])

In [99]:
'''
TO SET A SEED:
Something to note here is that when you're using random data
and you're running different tests on it,
it's very useful to be able to actually set a seed
and the seed is used to set a random state so
that the random results can actually be reproduced.
Keep in mind the results themselves are still random,
but you're choosing an arbitrary seed number so
that you get a particular set of random numbers.
'''
np.random.seed(42)
#usually used 42 in reference to hitchers guide to the galaxi book
np.random.rand(4)
#be aware of doing it all in the same cell!
#what seed allows it to set a particular set of random numbers
#very important to be able to repeat random distributions in order to test different models on them and different visualization methods


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [107]:
#the importatn thing is as long as you put those two in the same cell, youll be given the same exact numbers again
np.random.seed(42)
np.random.rand(5)
#if you add more, the firsts are the same as long as you keep the 42 seed but adds you more of those pre-stablisez random numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [113]:
#ATTRIBUTES AND METHODS FOR NUMPY ARRAYS:
arr = np.arange(0,25)

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [127]:
arr.reshape(5,5)
#can reshape an existing array in the form i waht (2D f ex)
#be careful of enetering a shape that can fit all the elements you got in the array
#test it by multiplying the two numbers you put and that should be equal to the number of elements you got originally

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [129]:
ranarr = np.random.randint(0,101,10)

In [133]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [137]:
ranarr.max()
#gives me the max or highest value in the array

99

In [141]:
ranarr.min()
#gives me the min or lowest value in the array

2

In [145]:
#to know the index location of these elements:
ranarr.argmax()
#that max arg is found in that index location

5

In [147]:
ranarr.argmin()
#that min arg is found in that index location

7

In [151]:
#to call the data type of an array:
ranarr.dtype

dtype('int32')

In [153]:
ones = np.ones((4,4))
ones.dtype

dtype('float64')

#the 32 or 64 are the numbers of bit the computers actually holding on - will depend of the precision its using for¿? memory

In [191]:
array = np.random.randint(0,101,10)

In [193]:
array

array([57, 21, 88, 48, 90, 58, 41, 91, 59, 79])

In [197]:
array.shape
#will tell me the shape of the array --> line, matrix,... as (ROWS, COLUMNS) as always
#it says 10,nothing to note that it is a 1D!!! 2D would be the 10,0 but then id have 4[]'s inside to note it

(10,)

In [199]:
array = array.reshape(2,5)

array([[57, 21, 88, 48, 90],
       [58, 41, 91, 59, 79]])

In [211]:
array.shape
#should put (2,5)¿?

(10,)