In [3]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#TO SELECT AN ELEMENT:
arr[8]
#remember it starts in zero!

8

In [21]:
#TO SELECT A SLICE OF ELEMENTS:
arr[0:5]
#can do the same but w a starting and an ending position (the ending position not included)

array([0, 1, 2, 3, 4])

In [25]:
arr[:5]
#start at the beggining and go up to 5 (not included) --> [:5] = [0:5]

array([0, 1, 2, 3, 4])

In [27]:
arr[5:]
#start in 5 (included) and go all the way to the end (as i dont specify the end, the last number will be included this time
#nice so i dont have to know the exact length of the array to index all the way to the end

array([ 5,  6,  7,  8,  9, 10])

In [31]:
#BROADCASTING:
#NumPy arrays differ from normal Python lists because of this ability to broadcast.
'''
With lists in normal Python,you can only reassign parts of a list
with new parts of the same shape and size. 
And then you would also need then possibly reassign this to a new variable.
However, NumPy, you can actually broadcast a single value across a larger set of values.
'''
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[0:5] = 100
#makes me able to select a slice of the array and set it equal to smth (this i cannot do in python)
#100 has been broadcasted across those values y selected
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
'''
actually slicing a section of an array and setting it to a new variable 
will actually only act as a pointer to the original array
'''

'\nactually slicing a section of an array and setting it to a new variable \nwill actually only act as a pointer to the original array\n'

In [41]:
slice_of_arr = arr[0:5]

In [47]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
slice_of_arr[:] = 99
#this  [:] is to select all in that array


In [61]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
#this should be returning [99,99,99,99,99,5,6,7,8,9,10] cos the slice_of_arr works as a pointer
#dont know why it doesnt
#if i dont want the original arr to change, i should get a copy of arr and modify that one:
copy_arr = arr.copy()
copy_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
slice_of_copy = copy_arr[0:5]
slice_of_copy

array([0, 1, 2, 3, 4])

In [79]:
slice_of_copy[:] = 999
slice_of_copy

array([999, 999, 999, 999, 999])

In [83]:
copy_arr

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

In [87]:
#NOW IT WORKED YUJUUU, it changes the copy_arr cos i changed the slice_of_copy 
#and it works as a pointer to the copy_arr, but the originar arr is unmodified
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
#TO SELECT AND INDEX FROM 2D ARRAYS:

In [113]:
arr_2d = np.array([[5,10,15],[20,25,20],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 20],
       [35, 40, 45]])

In [115]:
#i only want 1 row --> ill have one dimension for rows and another for columns


In [119]:
arr_2d.shape

(3, 3)

In [123]:
#So index zero, we have number of rows. The index one, we have number of columns.
#That distinction is going to be important later on when we cover Pandas

In [127]:
arr_2d [0]

array([ 5, 10, 15])

In [131]:
arr_2d[1]

array([20, 25, 20])

In [135]:
arr_2d [0] [1]
#WE START ALWAYS AT ZERO!
#i can index into the row index to get one of the elements (column if seen that way)

10

In [141]:
#same i can intro it in the same []
arr_2d [0,1]

10

In [147]:
arr_2d [1,1]
#REMEMBER IT STARTS AT ZEEEROOOO

25

In [151]:
#SLICING IN 2D

In [165]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 20]])

In [167]:
#in data sets the rows usually stand for data points and the columns for features
#--> its unusual to do double subsets - normally you subserr either a whole row or a whole column

In [169]:
#CONDITIONAL SELECTION:

In [171]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
#I can broadcast a condition or a comparison out of this

In [177]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [179]:
#So I run that, and this returns back a NumPy array of boolean values where the index location matches up
#with the original data.

In [183]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [187]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [189]:
#now it will only return back the index locations of this boolean array where it happens to be true

In [191]:
'''
So again, the steps here I did was have some sort of original array, do a comparison operator,
which gives you back this boolean array, which you can then use to filter out your original array.
'''

'\nSo again, the steps here I did was have some sort of original array, do a comparison operator,\nwhich gives you back this boolean array, which you can then use to filter out your original array.\n'

In [199]:
#Can do all these at once:
arr[arr>4]
#Shorter way
#Pandas will allow me to do multiple comparissons at once

array([ 5,  6,  7,  8,  9, 10])

In [201]:
'''
So for right now, we just need to understand this basic idea
that I can perform a comparison within my array
and then pass that as my conditional selection filter.
'''

'\nSo for right now, we just need to understand this basic idea\nthat I can perform a comparison within my array\nand then pass that as my conditional selection filter.\n'

In [263]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
myarr


array([[5, 6],
       [8, 9]])

array([[4, 4],
       [4, 4]])

In [247]:
ss = subarr [1:, 1:]
ss[:] = 4
myarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])