In [7]:
import numpy as np

In [11]:
arr = np.arange(0,10)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#ARITHMETICS BTW ARRAYS AND ARITHMETICS BTW SCALAR AND ARRAYS

In [21]:
arrplus = arr + 5
#will perform it element by element
arrplus

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
subarr [:] = arrplus[arrplus>8] = 55
subarr

array([55, 55, 55, 55, 55, 55])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arrplus

array([ 5,  6,  7,  8, 55, 55, 55, 55, 55, 55])

In [37]:
#see arrplus is now indeondent of arr --> arr is the same and only arrplus is modified

In [39]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [43]:
arr + arr
#to be able to do this the two arrays must have the same size obv

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
d2_1 = np.array([[1,2,3],[1,2,3],[1,2,3]])
d2_1


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [59]:
d2_2 = np.array([[1,2,4],[1,2,3],[1,2,3]])
d2_2

array([[1, 2, 4],
       [1, 2, 3],
       [1, 2, 3]])

In [63]:
d2_1 + d2_2

array([[2, 4, 7],
       [2, 4, 6],
       [2, 4, 6]])

In [67]:
d2_1 * d2_2

array([[ 1,  4, 12],
       [ 1,  4,  9],
       [ 1,  4,  9]])

In [71]:
#numpy works different with divisions when divided by zero

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr / arr

C:\Users\mirlo\AppData\Local\Temp\ipykernel_18860\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [83]:
#it ll still output a result however itll give you a warning --> sustitutes the division by 0 w 'nan' (not a number)

In [3]:
#in python it doesnt let you but in numpy if 0/0 --> nan; int!=0/0 --> inf (infinite)
#--> numpy will let me do it but places a placeholder in that spot

In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
np.sin(arr)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [36]:
np.log(arr)
#we get a warning bc log of zero desnt make sense

C:\Users\mirlo\AppData\Local\Temp\ipykernel_21088\111955462.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [38]:
#can see other numpy universall function calls in their website

In [42]:
arr.sum()
#sums up elements in the array

45

In [48]:
arr.mean()
#average

4.5

In [52]:
arr.max()
#maximum value in the array

9

In [56]:
arr.var()
#varianza

8.25

In [60]:
arr.std()
#desviacion tipica

2.8722813232690143

In [62]:
#AXIS LOGIC (2D)

In [72]:
arr2d = np.arange(0,25).reshape(5,5)

In [74]:
arr2d.shape

(5, 5)

In [78]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
arr2d.sum()
#sums all

300

In [86]:
#if i wanna sum only rows or columns --> sum function takes 'axis parameters' 
# --> 'a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)''

In [90]:
arr2d.sum(axis=0)
#when i called shape, the first number was rows, so the '0' position reffers to rows
#and so putting axis=0 itll perform the operation ACROSS THE ROWS
#performs the operation across the index of shape refered to!!!

array([50, 55, 60, 65, 70])

In [94]:
arr2d.sum(axis=1)
#1 reffers to columns and so itll make the operation ACROSS the columns (not with them!!!)

array([ 10,  35,  60,  85, 110])